name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.7.12]  # Specify the Flutter version you are using

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit and widget tests
        run: flutter test

      - name: Generate test coverage report
        run: |
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/html

      - name: Run integration tests
        run: flutter drive --target=test_driver/app.dart

      - name: Performance test
        run: |
          flutter drive --target=test_driver/performance.dart
          mkdir -p build/performance-results
          mv build/performance*.json build/performance-results/

      - name: Upload performance results
        uses: actions/upload-artifact@v2
        with:
          name: performance-results
          path: build/performance-results/

      - name: Post test results to Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Tests completed!"}' https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX